### ISSUE TITLE
Add class to input

### ISSUE THREAD

**Issue by tmartineau** [instructure/ic-autocomplete#17]
Would be nice to have a way to bind classes to the input, I tried looking around and I could not find anything that would allow this.

**Comment by rigelinside** [comment]
Yes it would be nice ..I am not able to add bootstrap class="form-control" to  ic-autocomplete.

**Comment by seifsallam** [comment]
:+1:

**Comment by ryanflorence** [comment]
The way this is built, you are able to make your own template and add whatever classes you'd like to your input.

https://github.com/instructure/ic-autocomplete/blob/master/lib/templates/autocomplete.hbs

Just make a template that looks nearly identical to this and you're all set.
