### ISSUE TITLE
Can't type space

### ISSUE THREAD

**Issue by novaugust** [instructure/ic-autocomplete#6]
Try typing "New York" into the input and you won't be able to get past "New"

**Comment by ryanflorence** [comment]
Apps are responsible for the filtering, so it's a bug in the demo not the lib, but I'll fix it today, thanks!

**Comment by ryanflorence** [comment]
actually, maybe its the autocomplete functionality in the component ...

**Comment by novaugust** [comment]
Ha, glad to have not wasted your time :)

**Comment by ryanflorence** [comment]
thanks :)

**Comment by ryanflorence** [comment]
alright, v0.0.4 released, demos show the fix, thanks again.
